### PR TITLE
Improve error messages and logging in the client

### PR DESCRIPTION
**Pull request by nlewo**
First of all, thanks for this library and the Terraform provider!

The commit contains the following changes:
- Error messages contain the context
- Switch from `fmt.Println` to `log.Println`
  `log.Println` outputs messages on `stderr` which is consumed by
  Terraform. This allows Terraform to output the logs of the Gandi
  provider (if switched to debug mode).
- HTTP request and response are outputed on a single line to get nice
  logs in Terraform
- HTTP request is outputed as a curl request to ease troubleshooting

From the (patched) Terraform provider, the outputs would now looks like:
```
2021-11-10T10:47:54.159+0100 [DEBUG] provider.terraform-provider-gandi: 2021/11/10 10:47:54 Request:  curl -X 'POST' -d '{"location":"FR","type":{"database":{"name":"mysql","version":""},"language":{"name":"php","version":""}},"name":"create","size":""}' -H 'Authorization: Apikey bla' -H 'Content-Type: application/json' 'http://STAGE/v5/simplehosting/instance'
2021-11-10T10:47:54.269+0100 [DEBUG] provider.terraform-provider-gandi: 2021/11/10 10:47:54 Response : [404 Not Found] Content-Length: [38] Connection: [keep-alive] Etag: [W"] Server: [nginx] Date: [Wed, 10 Nov 2021 09:47:54 GMT] Content-Type: [application/json; charset=utf-8] 
2021-11-10T10:47:54.269+0100 [DEBUG] provider.terraform-provider-gandi: 2021/11/10 10:47:54 Response body: {"message":"Resource does not exist."}
```

### CODE REVIEW

**Comment by tiramiseb** [comment]
Sorry, I had to revert this commit. I accepted the PR too quickly.

* Could you please replace "%s" with "%w" in the calls to fmt.Errorf?
* Is http2curl really necessary?
* Please avoid mixing imports in the go file header
* Please replace `log.Println(fmt.Sprintf` with `log.Printf`

Thanks

**Comment by nlewo** [comment]
I pushforced in my branch the following changes:
- replace "%s" with "%w" in the calls to fmt.Errorf
- replace log.Println(fmt.Sprintf with log.Printf

I could open a new PR with this commit if easier for you. Otherwise, i think you have to get the commit from my fork.

Using `http2curl`  allows to have a common representation of the request on a single line: we all know the CURL syntax. Moreover, the `http2curl` library doesn't have any dependencies, so it doesn't have a important impact the closure size of the library.
(OpenStack clients prints a CURL expression in debug mode and i always like this feature.)
Otherwise, if you prefer, I could print the request headers, url and data on a single line (but it's less readable than the CURL expression:)).

I'm not sure to undertand what you mean by "mixing imports": imports are lexicographically
ordered by `go fmt`.

**Comment by nlewo** [comment]
There is actually an issue since the `resp.Body` reader is consumed in `doAskGandi` and can be used by `askGandi`...

**Comment by nlewo** [comment]
I added a fixup commit in my branch. `doAskGandi` would now return the `(header, body, error)`: so we would only have to read the body once.

Since the API never returns big objects, i think we could consume the Reader and then manipulate the body as a `[]byte` object. 
WDYT?

**Comment by tiramiseb** [comment]
I'd prefer a new commit, yes.

I'm okay for the cURL expression only if it is used elsewhere in terraform. I don't think so, but I may be wrong...

Regarding imports, I use goimports. See https://goinbigdata.com/goimports-vs-gofmt/

**Comment by nlewo** [comment]
My plan is to enable go-gandi debug logs in Terraform when `TF_LOG=DEBUG` is provided to Terraform.

When this environment variable is set, the Terraform output would looks like:
```
2021-11-10T10:47:54.159+0100 [DEBUG] provider.terraform-provider-gandi: 2021/11/10 10:47:54 Request:  curl -X 'POST' -d '{"location":"data...}' -H 'Authorization: Apikey bla' -H 'Content-Type: application/json' 'http://STAGE/v5/simplehosting/instance'
```
In case of an issue, this allows to easily debug the query sent to Gandi since it is possible to copy/paste the request in the shell in order to manually replay what the provider did.

But, this is a cosmetic stuff. If you prefer, i could remove this library and manually print the request. 
I however think it would be better to only print single lines in order to have clean logs (instead of the multiline string outputed by the `DumpRequest` function).

I will use goimports and open a new PR.

**Pull request merged**
