### PR TITLE
certificate: support certificate and immediate certificate fetch API

### PR DESCRIPTION
**Pull request by cofyc**
add two missing APIs:

* Retrieve certificate: https://api.gandi.net/docs/certificate/#v5-certificate-issued-certs-id-crt
* Intermediate certificate: https://api.gandi.net/docs/certificate/#v5-certificate-pem-type

### CODE REVIEW

**Review by nlewo — APPROVED** [review]
@cofyc thanks for your contribution.

I'm wondering in which context do you plan to use this API? (the go-gangi library is mainly used in the Gandi terraform provider context but it doesn't seem to be the case for this PR).

**Comment by cofyc** [comment]
we wrote a program to sync certificates bought from gandi.net to vault

**Comment by nlewo** [comment]
@cofyc Ah cool! Do you plan to publish this program?

**Comment by cofyc** [comment]
right now it's just a small script used in our infrastructure, not a complete project yet ;-)

**Pull request merged**
