### PR TITLE
Improve error messages and logging in the client

### PR DESCRIPTION
**Pull request by nlewo**
This is the same PR than https://github.com/go-gandi/go-gandi/pull/33 with some fixes, as discussed in #33.

- Error messages contain the context
- Switch from fmt.Println to log.Printf
  log.Println outputs messages on stderr which is consumed by
  Terraform. This allows Terraform to output the logs of the Gandi
  provider.
- HTTP request and response are outputed on a single line to get nice
  logs in Terraform
- HTTP request is outputed as a curl request to ease troubleshooting

### CODE REVIEW

**Comment by nlewo** [comment]
Hm, i'm not able to locally reproduce the CI error:
```
pre-commit run --show-diff-on-failure --color=always --all-files --show-diff-on-failure
Check Toml...........................................(no files to check)Skipped
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Check for merge conflicts................................................Passed
go fmt...................................................................Passed
go vet...................................................................Passed
go imports...............................................................Passed
go-mod-tidy..............................................................Passed
golangci-lint............................................................Passed
prettier.................................................................Passed


```

**Comment by tiramiseb** [comment]
You are using io.ReadAll (which is fine). However, the go.mod file states that this module works with Go 1.13.
I don't know why it works for you but not in the CI. Maybe you need to change go.mod in order to explicitly say it needs Go 1.16 (or Go 1.17, I love using the latest Go version)...

**Comment by tiramiseb** [comment]
It looks like pre-commit uses an older version of go.

I have accepted pre-commit recently because it looks nice, however I don't know how it works exactly, let me dit into it :-)

**Comment by tiramiseb** [comment]
I think it is okay now, could you please merge master into your branch?

Thanks

**Comment by nlewo** [comment]
@tiramiseb Ok, I rebased and CI is now green. Thank you.

**Pull request merged**
