### PR TITLE
Move types to a separate file within each package

### PR DESCRIPTION
**Pull request by robbyoconnor**
This makes it easier to read. Most developers have LSP set up so this should be fine

### CODE REVIEW

**Comment by tiramiseb** [comment]
@robbyoconnor are you confident all these types are distributed outside of the `internal` part ?

I would like **all internal types to remain internal**, and any type accessible outside to be defined, well, outside of `internal`... 
 Simply a matter of good practice :slightly_smiling_face:

**Comment by robbyoconnor** [comment]
This PR is on-top of #18

**Comment by tiramiseb** [comment]
I like separating as much stuff in different files (on some projects, I even have 1 file per function), so I'm okay with this!

**Comment by robbyoconnor** [comment]
@tiramiseb could I requst you add the `hacktoberfest-accepted` label so this counts for Hacktoberfest (both of them)?

**Comment by robbyoconnor** [comment]
@tiramiseb fixing that in a PR =)

**Pull request merged**
