### PR TITLE
ci: add a go test step

### PR DESCRIPTION
**Pull request by nlewo**

### CODE REVIEW

**Comment by nlewo** [comment]
So, let's see if it works:/

**Comment by tiramiseb** [comment]
Could you check if that can be added in pre-commit instead?
Thanks

**Comment by nlewo** [comment]
@tiramiseb the https://github.com/dnephin/pre-commit-golang project doesn't provide a way to run all Go tests (only some test tagged as `unit`). I interpret this such as: "if it's not implemented, it's because it's not a good idea".
Also, running tests on each commit is a bit annoying i think (because it takes time).

**Comment by tiramiseb** [comment]
good point :+1:

**Pull request merged**
